src/labs/urls.py
from django.urls import path

from labs import views

app_name = 'labs'

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
]

src/sat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from chat import views

import labs.urls
import custom_auth.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('chat/', views.ChatList.as_view()),
    path('', include(labs.urls)),
    path('', include(custom_auth.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/labs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify

from labs.validators import DateValidator


def task_upload_path(instance, filename):
    return '{0}/{1}'.format(
        slugify(instance.study_class, allow_unicode=True), filename
    )


class Discipline(models.Model):
    name = models.CharField(
        _('discipline name'),
        max_length=100,
        unique=True
    )

    class Meta:
        verbose_name = _('discipline')
        verbose_name_plural = _('disciplines')
        ordering = ('name',)

    def __str__(self):
        return self.name


class Group(models.Model):
    number = models.CharField(
        _('group number'),
        max_length=6,
        validators=[
            MinLengthValidator(6),
        ],
        unique=True
    )

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ('number',)

    def natural_key(self):
        return self.number

    def __str__(self):
        return str(self.number)


from custom_auth.models import Teacher, Student


class StudyClass(models.Model):
    discipline = models.ForeignKey(
        Discipline,
        on_delete=models.CASCADE,
        related_name='study_classes',
        related_query_name='study_class'
    )
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        related_name='study_classes',
        related_query_name='study_class'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        related_name='study_classes',
        related_query_name='study_class'
    )

    class Meta:
        verbose_name = _('study class')
        verbose_name_plural = _('study classes')
        unique_together = (('discipline', 'group'),)
        ordering = ('discipline', 'group',)

    def __str__(self):
        return '{dsc} {grp}'.format(dsc=self.discipline, grp=self.group)


User = get_user_model()


class Task(models.Model):
    title = models.CharField(
        _('title'),
        max_length=100
    )
    description = models.TextField(
        _('description'),
        null=True,
        blank=True
    )
    variants = models.ManyToManyField(
        User,
        related_name='variants',
        related_query_name='variant',
        through='TaskVariant',
        through_fields=('task', 'assignee')
    )
    deadline = models.DateField(
        _('deadline'),
        validators=[
            DateValidator(),
        ]
    )
    attachment = models.FileField(
        _('attachment'),
        upload_to=task_upload_path,
        null=True,
        blank=True
    )
    study_class = models.ForeignKey(
        StudyClass,
        on_delete=models.CASCADE,
        related_name='tasks',
        related_query_name='task',
        verbose_name=_('study class')
    )
    order = models.PositiveIntegerField(
        _('task number in study class')
    )

    class Meta:
        verbose_name = _('task')
        verbose_name_plural = _('tasks')
        unique_together = (('study_class', 'order'),)
        ordering = ('study_class', 'order',)

    def __str__(self):
        return '{title}'.format(title=self.title)

    def clean(self):
        data = super().clean()
        return data


class TaskVariant(models.Model):
    task = models.ForeignKey(Task, models.CASCADE)
    assignee = models.ForeignKey(User, models.CASCADE)
    variant = models.TextField(_("Variant"), null=True, blank=True)
    note = models.TextField(_("Note"), null=True, blank=True)


class Lesson(models.Model):
    study_class = models.ForeignKey(
        StudyClass,
        on_delete=models.CASCADE,
        related_name='lessons',
        related_query_name='lesson',
        verbose_name=_('study class')
    )
    date = models.DateField(_('date'))

    class Meta:
        verbose_name = _('lesson')
        verbose_name_plural = _('lessons')
        ordering = ('study_class', 'date',)

    def __str__(self):
        return '{date} {sc}'.format(date=self.date, sc=self.study_class)


class Attendance(models.Model):
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='attendances',
        related_query_name='attendance',
        verbose_name=_('student')
    )
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        related_name='attendances',
        related_query_name='attendance',
        verbose_name=_('lesson')
    )
    attendance = models.BooleanField(
        _('attendance'),
        default=True
    )

    class Meta:
        verbose_name = _('attendance')
        verbose_name_plural = _('attendances')
        ordering = ('lesson', 'student',)

    def __str__(self):
        return '{ls} {std} {atn}'.format(ls=self.lesson, std=self.student, atn=self.attendance)


class Mark(models.Model):
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        related_name='marks',
        related_query_name='mark',
        verbose_name=_('student')
    )
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        related_name='marks',
        related_query_name='mark',
        verbose_name=_('lesson')
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='marks',
        related_query_name='mark',
        verbose_name=_('task')
    )
    mark = models.CharField(
        _('mark'),
        max_length=128,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = _('mark')
        verbose_name_plural = _('marks')
        unique_together = (('student', 'task'),)
        ordering = ('lesson', 'task', 'student',)

    def __str__(self):
        return '{mrk}'.format(mrk=self.mark)

src/labs/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from labs.models import Task, Mark, Attendance, TaskVariant


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'study_class')

    def save(self, commit=True):
        from django.utils.timezone import now
        self.instance.deadline = now().date()
        self.instance.order = self.instance.study_class.tasks.all().count() + 1
        return super().save(commit)


class MarkSetForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ('mark', 'student', 'task')

    def __init__(self, data, *args, **kwargs):
        qs = self._meta.model.objects.filter(student=data.get('student'), task=data.get('task'))
        kwargs['instance'] = qs.first() if qs.exists else None
        self.lesson = None
        super().__init__(data, *args, **kwargs)

    def clean(self):
        cd = super().clean()
        current_day = now().date()
        lqs = cd['task'].study_class.lessons.filter(date__lte=current_day)
        if not lqs.exists():
            raise ValidationError(_("Can't find nearest lesson."))
        self.lesson = lqs.first()

    def save(self, commit=True):
        self.instance.lesson = self.lesson
        return super().save(commit)


class AttendanceSetForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = '__all__'


class TaskVariantForm(forms.ModelForm):
    class Meta:
        model = TaskVariant
        fields = '__all__'


TaskVariantFormSet = inlineformset_factory(
    Task, TaskVariant, form=TaskVariantForm,fields=['assignee', 'variant', 'note'], extra=3, can_delete=False
)

src/labs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.template.loader import get_template
from django.utils.formats import date_format
from django.utils.http import urlencode
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin

from sat.exceptions import BadRequest, PermissionDenied
from sat.views import AjaxableResponseMixin
from labs.models import Discipline, StudyClass, TaskVariant
from labs.forms import TaskForm, MarkSetForm, AttendanceSetForm, TaskVariantFormSet
from chat.views import ChatList
from custom_auth.views import UserPersonalInfoView


class UserContextMixin(LoginRequiredMixin, ContextMixin):
    def get_redirect_field_name(self):
        return None

    def handle_no_permission(self):
        redirect = super().handle_no_permission()
        self.request.session[super().get_redirect_field_name()] = self.request.get_full_path()
        return redirect

    def get_context_data(self, **kwargs):
        menu = {}
        if self.request.method == 'GET' and not self.request.is_ajax():
            user = self.request.user
            if user.is_teacher:
                menu.update({_("Teacher sector"): {
                    str(discipline): [
                        (str(study_class.group), urlencode({'action': 'get_study_class', 'pk': study_class.pk}))
                        for study_class in user.teacher.study_classes.filter(discipline__exact=discipline)
                    ] for discipline in Discipline.objects.filter(study_class__teacher__exact=user.teacher).distinct()
                }})
            if user.is_student:
                menu.update({_("Student sector"): {
                    str(user.student.group): [
                        (str(study_class.discipline), urlencode({'action': 'get_study_class', 'pk': study_class.pk}))
                        for study_class in user.student.group.study_classes.all()
                    ]
                }})
        return super().get_context_data(**kwargs, **{'menu': menu})


class DashboardView(UserContextMixin, AjaxableResponseMixin, TemplateView):
    template_name = 'labs/dashboard.html'

    def get_study_class(self, request, *args, **kwargs):
        if request.method != 'GET':
            raise BadRequest(
                {'reason': _("%s action must be requested through %s method.") % ('get_study_class', 'GET')}
            )
        if 'pk' not in request.GET:
            raise BadRequest({'reason': _("Required parameters missed.")})
        pk = request.GET['pk']
        sc = StudyClass.objects.get(pk=pk)
        lessons_list = sc.lessons.all()
        return self.response_class(request, 'labs/dashboard/workspace.html', context={
            'sc': sc,
            'lessons_list': lessons_list,
            'students_list': [
                (student, {
                    attendance.lesson_id: attendance
                    for attendance in student.attendances.filter(lesson__study_class=sc)
                }, {
                    mark.task_id: mark for mark in student.marks.filter(lesson__study_class=sc)
                }) for student in sc.group.students.all()
            ],
            'task_list': sc.tasks.all(),
            'can_create': request.user.has_perms(['labs.add_task'], obj=sc, as_user='teacher'),
            'can_change': request.user.has_perms(['labs.change_task'], obj=sc, as_user='teacher'),
            'can_delete': request.user.has_perms(['labs.delete_task'], obj=sc, as_user='teacher'),
        })

    def post_mark(self, request, *args, **kwargs):
        if request.method != 'POST':
            raise BadRequest({'reason': _("%s action must be requested through %s method.") % ('post_mark', 'POST')})
        if not request.user.is_teacher:
            raise PermissionDenied({'reason': _("Only teachers can set marks!")})
        form = MarkSetForm(data=request.POST)
        if form.is_valid() and request.user.has_perms(['labs.change_attendance'], obj=form.instance.task.study_class,
                                                      as_user='teacher'):
            form.save()
            return JsonResponse({
                'new_mark': str(form.instance),
                'new_date': date_format(form.instance.lesson.date)
            })
        else:
            raise BadRequest({'reason': form.errors}) if form.errors else PermissionDenied({'reason': _(
                "You have no permissions to edit this study class."
            )})

    def post_task(self, request, *args, **kwargs):
        if request.method != 'POST':
            raise BadRequest({'reason': _("%s action must be requested through %s method.") % ('post_task', 'POST')})
        if not request.user.is_teacher:
            raise PermissionDenied({'reason': _("Only teachers can create tasks!")})
        form = TaskForm(data=request.POST)
        formset = TaskVariantFormSet(request.POST)
        if form.is_valid() and formset.is_valid() and request.user.has_perms(
                ['labs.add_task'], obj=form.instance.study_class, as_user='teacher'
        ):
            task = form.save()
            formset.instance = task
            formset.save()
            return JsonResponse({
                'nav-link': """
                <a class="nav-item nav-link"
                   data-toggle="tab"
                   href="#nav-profile-{taskid}"
                   role="tab"
                   aria-controls="nav-profile"
                   aria-selected="false"
                >{taskname}</a>
                """.format(taskid=task.id, taskname=str(task)),
                'tab-pane': """
                <div class="tab-pane fade"
                     id="nav-profile-{taskid}"
                     role="tabpanel"
                     aria-labelledby="nav-profile-tab"
                     style="height: 100%;
                ">
                """.format(taskid=task.id) + get_template('labs/dashboard/lab_info.html').render(context={
                    'task': task,
                    'students_list': [
                        (student, {
                            attendance.lesson_id: attendance
                            for attendance in student.attendances.filter(lesson__study_class=task.study_class)
                        }, {
                             mark.task_id: mark for mark in student.marks.filter(lesson__study_class=task.study_class)
                         }) for student in task.study_class.group.students.all()
                    ],
                    'can_change': True,
                }) + """</div>""",
            })
        else:
            raise BadRequest({'reason': form.errors}) if form.errors else PermissionDenied({'reason': _(
                "You have no permissions to edit this study class."
            )})

    def post_attendance(self, request, *args, **kwargs):
        if request.method != 'POST':
            raise BadRequest(
                {'reason': _("%s action must be requested through %s method.") % ('post_attendance', 'POST')}
            )
        if not request.user.is_teacher:
            raise PermissionDenied({'reason': _("Only teachers can control attendance!")})
        form = AttendanceSetForm(data=request.POST)
        if form.is_valid() and request.user.has_perms(['labs.change_attendance'], obj=form.instance.lesson.study_class,
                                                      as_user='teacher'):
            form.save()
            return HttpResponse('+' if form.instance.attendance else '-')
        else:
            raise BadRequest({'reason': form.errors}) if form.errors else PermissionDenied({'reason': _(
                "You have no permissions to edit this study class."
            )})

    def get_chat_list(self, request, *args, **kwargs):
        if 'HTTP_X_REQUESTED_WITH' in request.META:
            del request.META['HTTP_X_REQUESTED_WITH']
        return ChatList.view(request, *args, **kwargs)

    def get_chat(self, request, *args, **kwargs):
        return ChatList.view(request, *args, **kwargs)

    def get_personal_info(self, *args, **kwargs):
        return UserPersonalInfoView.view(*args, **kwargs)

    def post_var(self, request, *args, **kwargs):
        var_id = int(request.POST['var'])
        field = request.POST['field']
        value = request.POST['value']
        qs = TaskVariant.objects.filter(id=var_id)
        if not qs.exists():
            raise BadRequest({'reason': 'Cannot find var with such id.'})
        if field not in {'variant', 'note'}:
            raise BadRequest({'reason': 'Unknown field.'})
        qs.update(**{field: value})
        return JsonResponse({'data': value})

src/templates/labs/dashboard/dashboard.html
{% extends 'site_base.html' %}
{% load static i18n %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/group_info.css' %}">
    <link rel="stylesheet" href="{% static 'css/lab_info.css' %}">
    <link rel="stylesheet" href="{% static 'css/issue.css' %}">
{% endblock %}
{% block left_menu %}
    {% for group_name, group_menu in menu.items %}
        {% if not forloop.first or not forloop.last %}
            <p class="left_menu_menu">{{ group_name }}</p>
        {% endif %}
        {% for menu_value, submenu in group_menu.items %}
            <p class="left_menu_menu">{{ menu_value }}</p>
            <ul class="left_menu_submenu_list">
            {% for  submenu_value in submenu %}
                <li class="left_menu_submenu" value="{{ submenu_value.1 }}">{{ submenu_value.0 }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
    {% endfor %}
{% endblock %}
{% block trailing_js %}
<script type="text/javascript">
    $(document).on('click', '.left_menu_submenu', function() {
        $.ajax({
            type: "GET",
            url: "/dashboard/",
            data: this.getAttribute('value'),
            success: function (response) {
                // console.log(response);
                $('div.main_content').html(response);
            },
            error: function (response) {
                console.log(response);
            }
        });
    });
    {% if user.is_teacher %}
    $(document).on('click', 'td.mark', function (event) {
        event.preventDefault();
        let student_id = 0;
        let task_id = 0;
        for (let i=0, l=this.classList.length; i<l; ++i) {
            if(/student-.*/.test(this.classList[i])) student_id = this.classList[i].split('-')[1];
            if(/task-.*/.test(this.classList[i])) task_id = this.classList[i].split('-')[1];
        }
        if (!student_id || !task_id) return;
        this.setAttribute('value', $(this).html());
        this.classList.replace('mark', 'mark-edit');
        $(this).html(
            '<form id="setMark" method="post">' + '{% csrf_token %}' +
            '<input type="hidden" name="action" value="post_mark">' +
            '<input type="hidden" name="student" value="' + student_id + '"><input type="hidden" name="task" value="' + task_id + '">' +
            '<input type="text" name="mark"><input type="submit" value="Save"><input type="reset" value="Cancel">' +
            '</form>'
        );
    });
    $(document).on('submit', '#setMark', function (event) {
        event.preventDefault();
        let parent = this.parentNode;
        let this_form = this;
        let form_data = {};
        $.each($(this).serializeArray(), function () {
            form_data[this.name] = this.value;
        });
        if (!form_data['mark']) {
            this.reset();
            return;
        }
        $.ajax({
            type: this.method,
            url: '/dashboard/',
            data: $(this).serialize(),
            success: function (response) {
                parent.classList.replace('mark-edit', 'mark');
                $(parent).html(response.new_mark);
                console.log($(parent).parent().find('.date'));
                $(parent).parent().find('.date').html(response.new_date);
                parent.removeAttribute('value');
            },
            error: function (response) {
                console.log(response);
                this_form.reset();
            }
        });
    });
    $(document).on('reset', '#setMark', function (event) {
        event.preventDefault();
        let parent = this.parentNode;
        parent.classList.replace('mark-edit', 'mark');
        $(parent).html(parent.getAttribute('value'));
        parent.removeAttribute('value');
    });
    $(document).on('submit', '#createTask', function (event) {
        event.preventDefault();
        $.ajax({
            type: this.method,
            url: '/dashboard/',
            data: $(this).serialize(),
            success: function (response) {
                console.log(response);
            },
            error: function (response) {
                console.log(response);
            }
        });
    });
    $(document).on('click', 'th.attendance', function (event) {
        event.preventDefault();
        let student_id = 0;
        let lesson_id = 0;
        for (let i=0, l=this.classList.length; i<l; ++i) {
            if(/student-.*/.test(this.classList[i])) student_id = this.classList[i].split('-')[1];
            if(/lesson-.*/.test(this.classList[i])) lesson_id = this.classList[i].split('-')[1];
        }
        if (!student_id || !lesson_id) return;
        this.setAttribute('value', $(this).html());
        let checked = '';
        if ($(this).html() === '+') checked = ' checked';
        this.classList.replace('attendance', 'attendance-edit');
        $(this).html(
            '<form id="setAttendance" method="post">' + '{% csrf_token %}' +
            '<input type="hidden" name="action" value="post_attendance">' +
            '<input type="hidden" name="student" value="' + student_id + '"><input type="hidden" name="lesson" value="' + lesson_id + '">' +
            '<input type="checkbox" name="attendance"' + checked + '><input type="submit" value="Save">' +
            '</form>'
        );
    });
    $(document).on('submit', '#setAttendance', function (event) {
        event.preventDefault();
        let parent = this.parentNode;
        $.ajax({
            type: this.method,
            url: '/dashboard/',
            data: $(this).serialize(),
            success: function (response) {
                $(parent).html(response);
                parent.classList.replace('attendance-edit', 'attendance');
                parent.removeAttribute('value');
            },
            error: function (response) {
                console.log(response);
                $(parent).html(parent.getAttribute('value'));
                parent.classList.replace('attendance-edit', 'attendance');
                parent.removeAttribute('value');
            }
        });
    });
    {% endif %}
    $(document).on('click', '.user-info', function (event) {
        event.preventDefault();
        $.ajax({
            type: 'GET',
            url: '/dashboard/',
            data: {
                'action': "get_personal_info",
                'uid': this.id,
            },
            success: function (response) {
                $("div.main_content").html(response);
            },
            error: function (response) {
                console.log(response);
            }
        });
    });
</script>
{% endblock %}

src/templates/labs/dashboard/group_info.html
{% load labs_helpers %}
<div class="student_list" >
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>
                <th class="number_header" scope="col">№</th>
                <th class="fio_header" scope="col">ФИО</th>
                {% for lesson in lessons_list %}
                    <th class="date_header" scope="col">{{ lesson.date|date }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
        {% for student, attandences, marks in students_list %}
            <tr>
                <th scope="row" >{{ forloop.counter }}</th>
                <td class="user-info" id="{{ student.user_id }}">{{ student.user|stringformat:"s" }}</td>
                {% for lesson in lessons_list %}
                    {% with attandences|get_item:lesson.id as attandence %}
                    <th class="date_header attendance{% if can_change %} editable{% endif %} student-{{ student.user.pk }} lesson-{{ lesson.pk }}" scope="col">{% if not attandence %}{% elif attandence.attendance %}+{% else %}-{% endif %}</th>
                    {% endwith %}
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

src/templates/labs/dashboard/issue.html
<form id="createTask" method="post" style="height: 100%">{% csrf_token %}
<input type="hidden" name="taskvariant_set-TOTAL_FORMS" value="{{ students_list|length|add:1 }}" id="id_taskvariant_set-TOTAL_FORMS">
<input type="hidden" name="taskvariant_set-INITIAL_FORMS" value="0" id="id_taskvariant_set-INITIAL_FORMS">
<input type="hidden" name="taskvariant_set-MIN_NUM_FORMS" value="0" id="id_taskvariant_set-MIN_NUM_FORMS">
<input type="hidden" name="taskvariant_set-MAX_NUM_FORMS" value="1000" id="id_taskvariant_set-MAX_NUM_FORMS">
<input type="hidden" name="action" value="post_task">
<input type="hidden" name="study_class" value="{{ sc.pk }}">
    <div class="task_name_area">
        <input type="text" class="task_name" name="title" placeholder="Название лабораторной работы">
    </div>
    <div class="issue">
        <div class="task_table_area" >
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr>
                        <th class="number_header" scope="col">№</th>
                        <th class="fio_header" scope="col">ФИО</th>
                        <th class="option_header" scope="col">Вариант</th>
                        <th class="node_header" scope="col">Примечание</th>
                    </tr>
                </thead>
                <tbody>
                {% for student, attandences, marks in students_list %}
                    <tr>
                        <th scope="row" >{{ forloop.counter }}</th>
                        <td>{{ student.user|stringformat:"s" }}</td>
                        <td><input type="text" class="option_input" name="taskvariant_set-{{ forloop.counter }}-variant"></td>
                        <td><input type="text" class="node_input" name="taskvariant_set-{{ forloop.counter }}-note"></td>
                    </tr>
                    <input type="hidden" name="taskvariant_set-{{ forloop.counter }}-assignee" value="{{ student.user_id }}">
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="task_area">
            <div class="task_text_area">
                <textarea class="task_text" name="description" placeholder="Введите текст задания"></textarea>
                <div class="attach_btn_area">
                    <button class="attach_btn" type="submit">Выберите файл</button>
                </div>
            </div>
            <div class="task_files">

            </div>
        </div>
    </div>
    <div class="issue_btn_area">
        <button class="issue_btn" type="submit">Выдать</button>
    </div>
</form>

src/templates/labs/dashboard/lab_info.html
{% load labs_helpers %}
<div class="lab_info">
    <div class="student_list" >
        <table class="table table-hover">
            <thead class="thead-light">
                <tr>
                    <th class="number_header" scope="col">№</th>
                    <th class="fio_header" scope="col">ФИО</th>
                    <th class="date_header" scope="col">Дата сдачи</th>
                    <th class="mark_header" scope="col">Отметка</th>
                    <th class="option_header" scope="col">Вариант</th>
                    <th class="node_header" scope="col" style="width: 35%">Примечание</th>
                </tr>
            </thead>
            <tbody>
            {% for student, attandences, marks in students_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    {% with marks|get_item:task.id as mark %}
                        <td>{{ student.user|stringformat:"s" }}</td>
                            <td class="date">{% if mark %}{{ mark.lesson.date|date }}{% else %}-{% endif %}</td>
                            <td class="mark{% if can_change %} editable{% endif %} student-{{ student.user.pk }} task-{{ task.pk }} {% if not mark %}no-mark{% endif %}">{% if mark %}{{ mark|stringformat:"s" }}{% else %}-{% endif %}</td>
                    {% endwith %}
                    {% with student.user|get_task_variant:task as var %}
                        <td class="var variant{% if can_change %} editable {% if var %}id-{{ var.id }}{% else %}no-var{% endif %}{% endif %}">{% if var %}{{ var.variant }}{% endif %}</td>
                        <td class="var note{% if can_change %} editable {% if var %}id-{{ var.id }}{% else %}no-var{% endif %}{% endif %}">{{ var.note }}</td>
                    {% endwith %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="task_area">
        <div class="task_text_area">
            <p class="task_text">{{ task.description }}</p>
        </div>
        <div class="task_files">

        </div>
    </div>
</div>
{% if not can_change %}
    <style>
        .lab_info {
            height: 95%;
        }
    </style>
    <div class="ask_btn_area">
            <button class="ask_btn" type="submit">Задать вопрос</button>
    </div>
{% endif %}

src/templates/labs/dashboard/workspace.html
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist" style="border-bottom: none">
        <a class="nav-item nav-link active" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">{{ sc|stringformat:"s" }}</a>
        {% for task in task_list %}
            <a class="nav-item nav-link" data-toggle="tab" href="#nav-profile-{{ task.id }}" role="tab" aria-controls="nav-profile" aria-selected="false">{{ task|stringformat:"s" }}</a>
        {% endfor %}
        {% if can_create %}
            <a class="nav-item nav-link" data-toggle="tab" href="#nav-issue" role="tab" aria-controls="nav-contact" aria-selected="false">+</a>
        {% endif %}
    </div>
</nav>
<div class="tab-content" id="nav-tabContent" style="height: 95%; padding-top: 10px">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" style="height: 100%;">{% include 'labs/dashboard/group_info.html' %}</div>
    {% for task in task_list %}
        <div class="tab-pane fade" id="nav-profile-{{ task.id }}" role="tabpanel" aria-labelledby="nav-profile-tab" style="height: 100%;">{% include 'labs/dashboard/lab_info.html' %}</div>
    {% endfor %}
    {% if can_create %}
        <div class="tab-pane fade" id="nav-issue" role="tabpanel" aria-labelledby="nav-contact-tab" style="height: 100%;">{% include 'labs/dashboard/issue.html' %}</div>
    {% endif %}
</div>